"use client";

import { useEffect, useState } from "react";
import { api, BlogPost } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Loader2, ArrowLeft, Calendar, User, Share2 } from "lucide-react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";

export default function BlogPostPage() {
    const { id } = useParams();
    const [post, setPost] = useState<BlogPost | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (id) {
            fetchPost(id as string);
        }
    }, [id]);

    const fetchPost = async (postId: string) => {
        try {
            const response = await api.get(`/blog/${postId}`);
            setPost(response.data);
        } catch (error) {
            console.error("Failed to fetch blog post", error);
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <div className="flex items-center justify-center py-20">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
        );
    }

    if (!post) {
        return (
            <div className="flex flex-col items-center justify-center py-20 text-center">
                <h2 className="text-2xl font-bold mb-4">Post not found</h2>
                <Button asChild>
                    <Link href="/blog">Back to Blog</Link>
                </Button>
            </div>
        );
    }

    return (
        <div className="mx-auto max-w-3xl space-y-8 pb-12">
            <Button variant="ghost" size="sm" asChild className="mb-4">
                <Link href="/blog">
                    <ArrowLeft className="mr-2 h-4 w-4" />
                    Back to Blog
                </Link>
            </Button>

            <article className="prose prose-lg dark:prose-invert max-w-none">
                <div className="space-y-4 mb-8 not-prose">
                    <Badge variant="secondary" className="mb-2">
                        AI Generated
                    </Badge>
                    <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl">
                        {post.title}
                    </h1>
                    <div className="flex items-center text-muted-foreground space-x-4">
                        <div className="flex items-center">
                            <Calendar className="mr-2 h-4 w-4" />
                            {new Date(post.date).toLocaleDateString()}
                        </div>
                        <div className="flex items-center">
                            <User className="mr-2 h-4 w-4" />
                            Facta AI
                        </div>
                    </div>
                </div>

                {post.imageUrl && (
                    <div className="aspect-video w-full overflow-hidden rounded-xl mb-8 not-prose">
                        <img
                            src={post.imageUrl}
                            alt={post.title}
                            className="h-full w-full object-cover"
                        />
                    </div>
                )}

                <div className="whitespace-pre-wrap leading-relaxed">
                    {post.content}
                </div>
            </article>

            <div className="border-t pt-8 mt-8 flex justify-between items-center">
                <p className="text-muted-foreground text-sm">
                    This content was generated by AI based on analyzed claims.
                </p>
                <Button variant="outline" size="sm">
                    <Share2 className="mr-2 h-4 w-4" />
                    Share
                </Button>
            </div>
        </div>
    );
}
