export const mockResponses = [
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.google.com',
    accuracy: 80,
    payload: {
      title: 'Climate Change Article Analysis',
      body: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora, consequatur dolores blanditiis exercitationem sint vel excepturi reiciendis quia pariatur quasi odit ipsum, rerum corrupti eius odio consequuntur molestias possimus natus.',
    },
    cached: false,
    createdAt: '2021-01-01',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.wikipedia.org',
    accuracy: 85,
    payload: {
      title: 'History of Renewable Energy',
      body: 'An overview of how wind, solar, and hydro power evolved through centuries, with key breakthroughs and policy impacts.',
    },
    cached: true,
    createdAt: '2021-02-15',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://developer.mozilla.org',
    accuracy: 95,
    payload: {
      title: 'MDN Web Docs Overview',
      body: 'A deep dive into documentation and resources for front-end and back-end web development from Mozilla.',
    },
    cached: false,
    createdAt: '2021-03-10',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.nasa.gov',
    accuracy: 74,
    payload: {
      title: 'Mars Rover Mission Report',
      body: 'Details of the latest rover’s findings, including rock composition, soil samples, and atmospheric data.',
    },
    cached: false,
    createdAt: '2021-04-22',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.medium.com',
    accuracy: 82,
    payload: {
      title: 'Design Patterns in JavaScript',
      body: 'Exploring the singleton, observer, and factory patterns in modern JavaScript applications.',
    },
    cached: true,
    createdAt: '2021-05-30',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.github.com',
    accuracy: 97,
    payload: {
      title: 'Open Source Contributions',
      body: 'A guide to contributing to public repositories, handling pull requests, and writing clear commit messages.',
    },
    cached: false,
    createdAt: '2021-06-14',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.stackoverflow.com',
    accuracy: 92,
    payload: {
      title: 'Top JavaScript Questions',
      body: 'A curated list of most-asked questions about closures, promises, and async/await with solutions.',
    },
    cached: true,
    createdAt: '2021-07-18',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.nytimes.com',
    accuracy: 40,
    payload: {
      title: 'Global Tech Trends',
      body: 'An article analyzing how AI, blockchain, and quantum computing are shaping the future economy.',
    },
    cached: false,
    createdAt: '2021-08-02',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.openai.com',
    accuracy: 94,
    payload: {
      title: 'AI Research Highlights',
      body: 'Recent innovations in natural language processing, reinforcement learning, and generative models.',
    },
    cached: true,
    createdAt: '2021-09-09',
  },
  {
    id: crypto.randomUUID(),
    status: 'success',
    inputType: 'url',
    input: 'https://www.producthunt.com',
    accuracy: 87,
    payload: {
      title: 'Best Startup Launches',
      body: 'A roundup of promising new tools, apps, and services released in the last quarter.',
    },
    cached: false,
    createdAt: '2021-10-19',
  },
];
